apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: billings.billing.example.com
spec:
  group: billing.example.com
  names:
    kind: Billing
    listKind: BillingList
    plural: billings
    singular: billing
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Billing is the Schema for the billings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BillingSpec defines the desired state of Billing
          properties:
            amount:
              description: Amount of the money to be entered in the bill
              type: string
            name:
              description: Name of the person whose name is to be entered in the bill
              type: string
          type: object
        status:
          description: BillingStatus defines the observed state of Billing
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
